### ISSUE TITLE
Source for linker scripts and assembler code

### ISSUE THREAD

**Issue by AlanFord** [MayaPosch/Nodate#11]
I would like to work on adding support for the STM32L4 series, specifically the NUCLEO-L432KC board.  Is there a source for the linker scripts and assembler code that you would recommend?  I've seen multiple versions in GitHub repositories, but am not sure which would be most appropriate for this use.

Thanks.

**Comment by MayaPosch** [comment]
Thank you, Alan :)

For Nodate I use the CMSIS device files from the ST Microelectronics GitHub. E.g. for STM32L4 I have just added support from this repository: https://github.com/STMicroelectronics/STM32CubeL4

Compiling the 'Pushy' example for the Nucleo-L432KC board profile seems to work. I do not have any STM32L4 boards to test on, but I'm fairly confident it should just work :)
