### ISSUE TITLE
Possible typo in rcc.cpp

### ISSUE THREAD

**Issue by AlanFord** [MayaPosch/Nodate#7]
Looking through your source code, I noticed the following (lines 88 - 91 of rcc.cpp):

#elif defined RCC_APB2ENR_IOPEEN
	(*portHandlesStatic)[RCC_PORT_D].exists = true;
	(*portHandlesStatic)[RCC_PORT_D].enr = &(RCC->APB2ENR);
	(*portHandlesStatic)[RCC_PORT_D].enable = RCC_APB2ENR_IOPEEN_Pos;

Should RCC_PORT_D be RCC_PORT_E in the last three lines?

Thanks for building this framework - I enjoyed your articles at Hackaday.

**Comment by MayaPosch** [comment]
Hi @AlanFord,

Thank you, I'm glad you're enjoying the Hackaday articles :)

You're correct that the port enums are incorrect for Port E in that section. Must have happened during some copy-pasta action. I have pushed a hopefully fixed version.
